
# DATABASE
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qcvbukkvoarpmmpkqpfr
spring.datasource.password=Meubel@2026Supabase


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# HIKARI
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


# CLOUDINARY
cloudinary.cloud-name=dbgi1tugi
cloudinary.api-key=682988231635948
cloudinary.api-secret=6xC-N88mQ2s761-3BNejfXz1JNw


# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meubelpendawa@gmail.com
spring.mail.password=mgxy wtbv oufm vtsl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# MIDTRANS
midtrans.server-key=Mid-server-A0fjl63HE5mf4fP9LM-PBOfb
midtrans.client-key=Mid-client-GxNCsGhxM0tBYafM
midtrans.is-production=false


# STRUK
struk.email-tujuan=meubelpendawa@gmail.com
laporan.email.tujuan=meubelpendawa@gmail.com


# SERVER
server.port=8080


# LOGGING (Development)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE